### ISSUE TITLE
Channel recognition problem

### ISSUE THREAD

**Issue by NathaelB** [mineralts/core#2]
**Describe the bug**
When launching the bot via the `yarn dev` command, the bot immediately returns an error.
__Error__:
```
/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/core/packets/GuildCreatePacket.js:51
                channel.parent = this.channels.get(channel.parentId);
                                                           ^

TypeError: Cannot read properties of undefined (reading 'parentId')
    at /Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/core/packets/GuildCreatePacket.js:51:60
    at Array.forEach (<anonymous>)
    at GuildCreatePacket.handle (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/core/packets/GuildCreatePacket.js:48:26)
    at /Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/assembler/Assembler.js:55:74
    at Array.map (<anonymous>)
    at /Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/assembler/Assembler.js:55:43
    at /Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/connector-preview/build/socket/index.js:70:13
    at Object.next (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/rxjs/dist/cjs/internal/Subscriber.js:161:21)
    at SafeSubscriber.Subscriber._next (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/rxjs/dist/cjs/internal/Subscriber.js:101:26)
    at SafeSubscriber.Subscriber.next (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
[esbuild-dev] process exited with 1
```

Note that when I redo the action with a bot present on a discord without the channels like announcements, rules or events, it lights up without clutter! 

**To Reproduce**
1. Create project
2. Put a bot token on a discord with atypical channels
3. Start the bot

**Expected behavior**

**Context (please use and past the following command : `node forge info`):**
 - OS: MacOS Big Sur `v11.4`

**Comment by LeadcodeDev** [comment]
I thank you for this issue, all types of channels have been added.
They will be available in the next version of the `core-preview`
