### ISSUE TITLE
Error with command

### ISSUE THREAD

**Issue by NathaelB** [mineralts/core#3]
**Describe the bug**
Problem encountered with the `node forge info` command
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '-r',
    '/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/esbuild-dev/pkg/child-process-registration.js',
    'node_modules/@mineralts/core-preview/build/core/standalone/Forge.js'
  ]
}
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: node /Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/esbuild-dev/pkg/esbuild-dev.bin.js node_modules/@mineralts/core-preview/build/core/standalone/Forge.js 
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Ignitor.execTypescript (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/core/standalone/Ignitor.js:73:38)
    at Ignitor.forge (/Users/nathael/Desktop/Hypolia/development/web/mineral/node_modules/@mineralts/core-preview/build/core/standalone/Ignitor.js:62:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 29902,
  stdout: null,
  stderr: null
}
```

**To Reproduce**
1. Create project
2. `yarn install`
3. `node forge info`

**Context (please use and past the following command : `node forge info`):**
 - OS: MacOS Big Sur `v11.4`

**Comment by UndefinedCoding** [comment]
![Sans titre-1](https://user-images.githubusercontent.com/40670392/151871820-80c201be-edf9-4fdb-8f35-bcf4aa32c466.png)
