### ISSUE TITLE
embed with no channels mentions

### ISSUE THREAD

**Issue by R3dlessX** [mineralts/core#5]
**Describe the bug**
```
E:\workspace\node_modules\@mineralts\core-preview\build\assembler\builders\MessageBuilder.js:17
        const channelMentions = payload.content.split(' ')
                                                ^

TypeError: Cannot read properties of undefined (reading 'split')
    at MessageBuilder.build (E:\workspace\node_modules\@mineralts\core-preview\build\assembler\builders\MessageBuilder.js:17:49)
    at MessageUpdatePacket.handle (E:\workspace\node_modules\@mineralts\core-preview\build\core\packets\MessageUpdatePacket.js:15:38)
    at E:\workspace\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:74
    at Array.map (<anonymous>)
    at E:\workspace\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:43
    at E:\workspace\node_modules\@mineralts\connector-preview\build\socket\index.js:70:13
    at Object.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:161:21)
    at SafeSubscriber.Subscriber._next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:101:26)
    at SafeSubscriber.Subscriber.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:72:18)
    at WebSocket.<anonymous> (E:\workspace\node_modules\@mineralts\connector-preview\build\socket\index.js:37:26)
```

**To Reproduce**
1. Create mineral instance and install dependencies.
2. Create command with an embed
 `    const embed = new MessageEmbed();
    embed.setTitle("Informations for test");
    await interaction.reply({embeds: [embed]
    });`

**Context (please use and past the following command : `node forge info`):**
```
{
  appName: '',
  appVersion: '1.0.0',
  appIntents: 32767,
  packages: { '@mineralts/core-preview': 'latest' },
  rcFile: {
    commands: [ '@mineralts/core-preview' ],
    aliases: { App: 'src', Config: 'config', Contracts: 'contracts' },
    preloads: [],
    providers: [],
    statics: []
  },
  commands: Collection(7) [Map] {
    'app:dev' => ApplicationDev { logger: [Logger], application: [Application] },
    'generate:manifest' => GenerateManifest { logger: [Logger], application: [Application] },
    'help' => GenerateManifest { logger: [Logger], application: [Application] },
    'info' => MakeCommand { logger: [Logger], application: [Application] },
    'make:command' => MakeCommand { logger: [Logger], application: [Application] },
    'make:event' => GenerateManifest { logger: [Logger], application: [Application] },
    'make:subcommand' => MakeSubcommand { logger: [Logger], application: [Application] }
  }
}
````
- OS: Windows 11

**Comment by LeadcodeDev** [comment]
I thank you for this issue, I just patched the bug.

The fix will be available in the next version !
