### ISSUE TITLE
Interaction error on an old slashcommand

### ISSUE THREAD

**Issue by R3dlessX** [mineralts/core#6]
**Describe the bug**
Mineral did not create the new slash commands and the old slash command was still present
```
E:\workspace\node_modules\@mineralts\core-preview\build\core\packets\CommandInteractionPacket.js:33
        await targetCommand.run(interaction);
                            ^

TypeError: Cannot read properties of null (reading 'run')
    at CommandInteractionPacket.handle (E:\workspace\node_modules\@mineralts\core-preview\build\core\packets\CommandInteractionPacket.js:33:29)
    at E:\ryuk\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:74
    at Array.map (<anonymous>)
    at E:\workspace\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:43
    at E:\workspace\node_modules\@mineralts\connector-preview\build\socket\index.js:70:13
    at Object.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:161:21)
    at SafeSubscriber.Subscriber._next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:101:26)
    at SafeSubscriber.Subscriber.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:72:18)
    at WebSocket.<anonymous> (E:\workspace\node_modules\@mineralts\connector-preview\build\socket\index.js:37:26)
    at WebSocket.emit (node:events:520:28)

Node.js v17.4.0


```

**Context (please use and past the following command : `node forge info`):**
```
{
  appName: '',
  appVersion: '1.0.0',
  appIntents: 32767,
  packages: { '@mineralts/core-preview': 'latest' },
  rcFile: {
    commands: [ '@mineralts/core-preview' ],
    aliases: { App: 'src', Config: 'config', Contracts: 'contracts' },
    preloads: [],
    providers: [],
    statics: []
  },
  commands: Collection(7) [Map] {
    'app:dev' => ApplicationDev { logger: [Logger], application: [Application] },
    'generate:manifest' => GenerateManifest { logger: [Logger], application: [Application] },
    'help' => GenerateManifest { logger: [Logger], application: [Application] },
    'info' => MakeCommand { logger: [Logger], application: [Application] },
    'make:command' => MakeCommand { logger: [Logger], application: [Application] },
    'make:event' => GenerateManifest { logger: [Logger], application: [Application] },
    'make:subcommand' => MakeSubcommand { logger: [Logger], application: [Application] }
  }
}
````
- OS: Windows 11

**Comment by LeadcodeDev** [comment]
Can you send me your command or subcommand code ?
