### ISSUE TITLE
Command: Option not required 

### ISSUE THREAD

**Issue by R3dlessX** [mineralts/core#7]
**Describe the bug**
Try to retrieve a boolean of information not required (so null)
```
E:\workspace\node_modules\@mineralts\core-preview\build\api\entities\interaction\CommandOptions.js:37
        return numberValue.value;
                           ^

TypeError: Cannot read properties of undefined (reading 'value')
    at CommandOptions.getBoolean (E:\workspace\node_modules\@mineralts\core-preview\build\api\entities\interaction\CommandOptions.js:37:28)
    at Serverinfo.run (E:\workspace\src\general\serverinfo\Serverinfo.ts:40:51)
    at CommandInteractionPacket.handle (E:\ryuk\node_modules\@mineralts\core-preview\build\core\packets\CommandInteractionPacket.js:33:29)
    at E:\ryuk\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:74
    at Array.map (<anonymous>)
    at E:\workspace\node_modules\@mineralts\core-preview\build\assembler\Assembler.js:55:43
    at E:\workspace\node_modules\@mineralts\connector-preview\build\socket\index.js:70:13
    at Object.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:161:21)
    at SafeSubscriber.Subscriber._next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:101:26)
    at SafeSubscriber.Subscriber.next (E:\workspace\node_modules\rxjs\dist\cjs\internal\Subscriber.js:72:18)

Node.js v17.4.0

```
**To Reproduce**
1. Create mineral instance and install dependencies.
2. Create command with an non required option
3. Try to get this option `interaction.commandOptions.getBoolean('YOUR BOOLEAN OPTION')`
4. Run the / command without this option

**Context (please use and past the following command : `node forge info`):**
```
{
  appName: '',
  appVersion: '1.0.0',
  appIntents: 32767,
  packages: { '@mineralts/core-preview': 'latest' },
  rcFile: {
    commands: [ '@mineralts/core-preview' ],
    aliases: { App: 'src', Config: 'config', Contracts: 'contracts' },
    preloads: [],
    providers: [],
    statics: []
  },
  commands: Collection(7) [Map] {
    'app:dev' => ApplicationDev { logger: [Logger], application: [Application] },
    'generate:manifest' => GenerateManifest { logger: [Logger], application: [Application] },
    'help' => GenerateManifest { logger: [Logger], application: [Application] },
    'info' => MakeCommand { logger: [Logger], application: [Application] },
    'make:command' => MakeCommand { logger: [Logger], application: [Application] },
    'make:event' => GenerateManifest { logger: [Logger], application: [Application] },
    'make:subcommand' => MakeSubcommand { logger: [Logger], application: [Application] }
  }
}
```
 - OS: WINDOWS 11

**Comment by LeadcodeDev** [comment]
I have patched this issue, the fix will be available in the next version of the `core-preview` library, thanks a lot !
